// const simple = require ("./Classes/Learnable/index")
// const obj1 = require("./Objects/Obj1/obj1")
// const obj2 = require("./Objects/obj2")
// const obj3 = require("./Objects/Obj3/obj3")
// const obj3 = require("./Objects/Obj4/obj4")
// const obj1 = require("./Objects/Obj5/obj5")
const obj1 = require("./Objects/Obj6/obj6")