// const simple = require ("./Classes/Learnable/index")
// const obj1 = require("./Objects/obj1")
// const obj2 = require("./Objects/obj2")
 const obj3 = require("./Objects/Obj3/obj3")
// const obj3 = require("./Objects/Obj4/obj4")